### PR TITLE
Added thermostat state changed flow trigger

### PR DESCRIPTION
**Pull request by slasktrat**
I was in need of a state change trigger and I guess that could be useful to others as well.

### CODE REVIEW

**Comment by slasktrat** [comment]
This was just a very quick implementation, you are more than welcome to improve it :)

**Comment by TedTolboom** [comment]
I will need to think about it...

Not because the state vs on/off... but I’m currently rewriting the app to SDK2 to be able to extend the app with all new devices ThermoFloor (through Heatit) are releasing.

For all my other apps, I’m trying to setup more generic / versatile flow cards... able to be used for multiple devices..

For the first gen thermostat I have to consider the “legacy” cards, to not upset multiple users by breaking their flows... 

for this one, I need to check not to create new legacy issues, just before releasing the SDK2 version...

**Comment by slasktrat** [comment]
Sure, I totally understand. I noticed just before submitting the pull request that you where working on a SDK2 branch, so I understand it's not the best time to introduce new features to the "legacy" branch.

If it's easier, you may very well consider this a feature request to the new app version instead of merging this pull request. :)

**Comment by TedTolboom** [comment]
Will be fullfilled with v2.0.1

**Pull request closed without merging**
